// Browser-automation parity test:
//   1. Open index.html in a real Chromium.
//   2. Pick the chr20 norealign tf.Example shard via the file input.
//   3. Wait for the page to finish wasm-decoding + ORT inference.
//   4. Assert all rows pass and Δ vs native is below tolerance.
//
// `expected.json` is generated by `build.sh` from a fresh native
// `dv call-variants` run on the same shard, so this test enforces
// bit-exact-ish parity between the in-browser path and native ORT.

import { test, expect } from '@playwright/test';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, '../..');
const TFRECORD = path.join(REPO, 'testdata/quickstart_chr20_norealign/examples.tfrecord.gz');

test('upload tf.Example shard, run wasm + onnxruntime-web, parity vs native', async ({ page }) => {
    const errs = [];
    page.on('pageerror', (e) => errs.push(`pageerror: ${e.message}`));
    page.on('console', (msg) => {
        if (msg.type() === 'error') errs.push(`console.error: ${msg.text()}`);
    });

    await page.goto('/index.html');

    // Use the file picker (this is the user-facing flow we want to verify).
    await page.setInputFiles('#file', TFRECORD);

    // Wait for inference to finish — the page sets status to "done — …".
    await expect(page.locator('#status')).toContainText('done', { timeout: 4 * 60 * 1000 });

    const summary = page.locator('#summary');
    const total = parseInt(await summary.getAttribute('data-total') ?? '0', 10);
    const pass = parseInt(await summary.getAttribute('data-pass') ?? '0', 10);
    const fail = parseInt(await summary.getAttribute('data-fail') ?? '0', 10);
    const maxDelta = await summary.getAttribute('data-max-delta') ?? '—';

    console.log(`browser run: ${pass}/${total} pass, ${fail} fail, max Δ=${maxDelta}`);

    expect(errs, `unexpected page errors: ${errs.join('\n')}`).toHaveLength(0);
    expect(total).toBeGreaterThan(0);
    expect(fail).toBe(0);
    expect(pass).toBe(total);

    // Spot-check a couple of rows so the test catches "everything was 0" silently.
    await expect(page.locator('[data-test="top-0"]')).not.toBeEmpty();
    await expect(page.locator('[data-test="probs-0"]')).toContainText(',');
});
